### ISSUE TITLE
om:Measure instances must appear in serialized output from opil_factory

### ISSUE THREAD

**Issue by rmarkelo** [SD2E/opil#16] opened 2020-10-06 15:00 UTC
The values for MeasureParameters are specified using instances of the om:Measure class. It's possible to instantiate om:Measure instances using pySBOL, but when this is done and the triples are serialized using opil_factory, the om:Measure instances are missing.

**Comment by bbartley** [comment] 2020-10-09 02:55
This appears to be caused by or at least related to https://github.com/SynBioDex/pySBOL3/issues/105

**Comment by bbartley** [comment] 2020-10-14 15:28
This problem turned out to have two underlying problems.  One was a bug in OPIL's autogenerated API, which was generating the `hasValueObject` incorrectly as an associative property rather than a compositional property. This first issue was fixed in:
https://github.com/SD2E/opil/pull/21

The second issue was an underlying issue in pySBOL, which was not properly handling compositional properties correctly (i.e., `OwnedObjectSingletonProperty`).  This was fixed in:
https://github.com/SynBioDex/pySBOL3/pull/106

**Closed by bbartley** 2020-10-14 15:28 UTC
