### ISSUE TITLE
Child object vs. reference

### ISSUE THREAD

**Issue by jakebeal** [SD2E/opil#136] opened 2021-02-11 10:39 UTC
A number of the child objects links are rendering as TopLevel objects, and should be changed to using black diamonds instead of clear diamonds.

The ones that I have noticed are:
- In ProtocolInterface: hasMeasurementType, hasParameter
- In ExperimentalRequest: hasMeasurement, hasParameterValue
- In Measurement: time

**Comment by bbartley** [comment] 2021-02-18 22:56
I can't reproduce this.  The relationships listed above are currently rendering using black diamonds.  Perhaps in the course of other updates, this got fixed somehow.  I'm going to close this for now, but will keep an eye out for similar occurrences.

**Comment by jakebeal** [comment] 2021-02-18 23:37
Can you please regenerate the OPIL spec entries then?

**Closed** 2021-02-22 20:21 UTC
